---
# Constants for the Configuration
version: "0.9.0"
identifier:
  id: 0
server_location: ~
background_process: ~
system_connection:
  - Media:
      all_stop_media: []
      media_map:
        ? id: 502
        : uri: "https://archive.org/download/Sintel-ThirdOpenMovieByBlenderFoundation/sintel-640-stereo.mp4"
          channel: 1
        ? id: 503
        : uri: "https://archive.org/download/Sintel-ThirdOpenMovieByBlenderFoundation/sintel-640-stereo.mp4"
          channel: 2
        ? id: 504
        : uri: "https://upload.wikimedia.org/wikipedia/commons/7/7a/George_Gershwin%27s_%22Rhapsody_in_Blue%22_piano_solo.ogg"
          channel: 3
      channel_map:
        ? 1
        : video_window:
            window_number: 1
            top: 0
            left: 0
            height: 270
            width: 512
          loop_media: "https://archive.org/download/Sintel-ThirdOpenMovieByBlenderFoundation/sintel-640-stereo.mp4"
        ? 2
        : video_window:
            window_number: 1
            top: 300
            left: 500
            height: 270
            width: 512
        ? 3
        : audio_device: ~ # Use the system default
        
default_scene:
  id: 100

# Scope Definitions
all_scenes:

  # Introduction Scene
  ? id: 100
  : events:
      - id: 100
      - id: 101
    key_map:
      ? 32
      : id: 101

  # Event Scene
  ? id: 200
  : events:
      - id: 200
      - id: 201
      - id: 202
      - id: 203
      - id: 204
      - id: 205
      - id: 206
    key_map:
      ? 32
      : id: 201

  # Status Scene
  ? id: 300
  : events:
      - id: 200
      - id: 7
      - id: 8
      - id: 9
      - id: 10
      - id: 11
    key_map:
      ? 32
      : id: 7
      ? 104
      : id: 9

  # Data Input, Output Scene
  ? id: 400
  : events:
      - id: 200
      - id: 7
      - id: 8
      - id: 9
      - id: 10
      - id: 11
    key_map:
      ? 32
      : id: 7
      ? 104
      : id: 9

  # Media Scene
  ? id: 500
  : events:
      - id: 500
      - id: 501
      - id: 502
      - id: 503
      - id: 504
    key_map:
      ? 32
      : id: 501


# Status Map
status_map:
  ? id: 20
  : MultiState:
      current: 
        id: 21
      allowed:
        - id: 21
        - id: 22
      no_change_silent: false

  ? id: 30
  : MultiState:
      current: 
        id: 31
      allowed:
        - id: 31
      no_change_silent: false


# Event Set
event_set:
  # Introduction Scene
  ? id: 100
    description: Introduction
    display: Hidden
  : []
  ? id: 101
    description: Next Scene
    display:
      DisplayWith:
        group_id:
          id: 110
        highlight: [100, 250, 0]
        spotlight: 0
  : - NewScene:
        new_scene:
          id: 200
  ? id: 110
    description: Click Below to Change Scenes
    display: Hidden

  # Event Scene
  ? id: 200
    description: Event Examples
    display:
      LabelHidden:
        position: ~
        color: [115, 210, 22]
  : []
  ? id: 201
    description: Next Scene
    display:
      DisplayWith:
        group_id:
          id: 210
  : - NewScene:
        new_scene:
          id: 300
  ? id: 202
    description: Trigger Delayed Events
    display:
      DisplayWith:
        group_id:
          id: 210
  : - CueEvent:
        event:
          delay:
            secs: 10
            nanos: 0
          event_id:
            id: 203
    - CueEvent:
        event:
          delay:
            secs: 11
            nanos: 0
          event_id:
            id: 204
    - CueEvent:
        event:
          delay:
            secs: 20
            nanos: 0
          event_id:
            id: 203
    - CueEvent:
        event:
          delay:
            secs: 30
            nanos: 0
          event_id:
            id: 203
    - CueEvent:
        event:
          delay:
            secs: 40
            nanos: 0
          event_id:
            id: 203
    - CueEvent:
        event:
          delay:
            secs: 50
            nanos: 0
          event_id:
            id: 203
  ? id: 203
    description: An Event
    display: Hidden
  : []
  ? id: 204
    description: Cancel Upcoming Events
    display:
      DisplayWith:
        group_id:
          id: 210
  : - CancelEvent:
        event:
          id: 203
    - CancelEvent:
        event:
          id: 204
  ? id: 205
    description: This Event Does Nothing
    display:
      DisplayWith:
        group_id:
          id: 210
  : []
  ? id: 206
    description: You Found Me! (Debug Only)
    display:
      DisplayDebug:
        group_id:
          id: 210
        color: [238, 204, 68]
  : []
  ? id: 210
    description: That's an Event! Try Again ...
    display: Hidden

  ? id: 5
    description: Reload Events Or Do Nothing
    display: 
      DisplayWith:
        group_id:
          id: 20
        position: ~
        color: ~
        highlight: [0, 255, 0]
        spotlight: 0
  : - GroupedEvent:
        status_id:
          id: 20
        event_map:
          ? id: 21
          : id: 2
          ? id: 22
          : id: 6


  # Media Scene
  ? id: 500
    description: Media Examples
    display: Hidden
  : []
  ? id: 501
    description: Back To Introduction
    display: 
      DisplayWith:
        group_id:
          id: 510
  : - NewScene:
        new_scene:
          id: 100
  ? id: 502
    description: Play Video At Top Left
    display:
      DisplayWith:
        group_id:
          id: 510
  : []
  ? id: 503
    description: Play A Second Video
    display:
      DisplayWith:
        group_id:
          id: 510
  : []
  ? id: 504
    description: Play Background Audio
    display:
      DisplayWith:
        group_id:
          id: 510
  : []
  ? id: 510
    description: You Can Play Media As Well
    display: Hidden


  ? id: 20
    description: Event Status
    display:
      LabelControl:
        position: ~
        color: ~
        highlight: ~
        highlight_state: ~
  ? id: 21
    description: Loading Delayed Events
    display:
      LabelHidden:
        color: [255, 161, 255]
  ? id: 22
    description: Doing Nothing
    display:
      LabelHidden:
        color: [51, 161, 255]
        highlight: [255, 0, 0]
        spotlight: 5
  ? id: 30
    description: Unchangeable Status
    display:
      LabelControl:
        position: ~
        color: ~
        highlight: ~
        highlight_state: ~
  ? id: 31
    description: Can't Change This
    display:
      LabelHidden:
        color: [255, 161, 255]


