version: 0.9.15
identifier:
  id: 0
server_location: redis://127.0.0.1:6379
dmx_path: null
media_players: []
system_connections:
- !Mercury
    path: /dev/ttyACM0
    use_checksum: true
- !ZmqPrimary
    send_path: "tcp://127.0.0.1:1111"
    recv_path: "tcp://127.0.0.1:2222"
background_process: null
default_scene:
  id: 100
group_map:
  ? id: 700
  : items:
    - id: 101
    is_hidden: false
scene_map:
  ? id: 100
  : items:
    - id: 100
    groups:
    - id: 700
    key_map: null
  ? id: 400
  : items:
    - id: 402
    - id: 400
    - id: 401
    groups: []
    key_map:
      32:
        id: 401
  ? id: 200
  : items:
    - id: 205
    - id: 204
    - id: 206
    - id: 201
    - id: 200
    - id: 203
    - id: 202
    groups: []
    key_map: null
  ? id: 300
  : items:
    - id: 302
    - id: 323
    - id: 312
    - id: 301
    - id: 314
    - id: 303
    - id: 324
    - id: 313
    - id: 304
    - id: 322
    - id: 311
    - id: 300
    - id: 321
    groups: []
    key_map: null
  ? id: 500
  : items:
    - id: 502
    - id: 504
    - id: 501
    - id: 503
    - id: 500
    groups: []
    key_map:
      32:
        id: 501
status_map:
  ? id: 310
  : !MultiState
    current:
      id: 311
    allowed:
    - id: 311
    - id: 312
    - id: 324
    no_change_silent: false
  ? id: 320
  : !MultiState
    current:
      id: 322
    allowed:
    - id: 321
    - id: 322
    no_change_silent: false
event_set:
  ? id: 101
    description: Next Scene
  : - !NewScene
      new_scene:
        id: 200
  ? id: 312
    description: Off
  : []
  ? id: 504
    description: Play Background Audio
  : []
  ? id: 410
    description: Send & Save Data
  : null
  ? id: 324
    description: Deactivate
  : - !ModifyStatus
      status_id:
        id: 320
      new_state:
        id: 322
  ? id: 313
    description: Turn On
  : - !ModifyStatus
      status_id:
        id: 310
      new_state:
        id: 311
  ? id: 320
    description: Change The Event
  : null
  ? id: 203
    description: An Event
  : []
  ? id: 321
    description: Trigger Delayed Events
  : []
  ? id: 302
    description: Variable Event
  : - !SelectEvent
      status_id:
        id: 320
      event_map:
        ? id: 322
        : id: 304
        ? id: 321
        : id: 303
  ? id: 100
    description: Introduction
  : []
  ? id: 700
    description: An Example Group
  : null
  ? id: 303
    description: Add Delayed Events
  : - !CueEvent
      event:
        delay:
          secs: 10
          nanos: 0
        event_id:
          id: 304
    - !CueEvent
      event:
        delay:
          secs: 20
          nanos: 0
        event_id:
          id: 304
  ? id: 310
    description: 'This Is A Status:'
  : null
  ? id: 502
    description: Play A Large Video
  : - !CueMedia
      cue:
        uri: https://archive.org/download/never-gonna-give-you-up-4-k/Never%20Gonna%20Give%20You%20Up%204K.ia.mp4
        channel: 1
        loop_media: null
  ? id: 400
    description: Data Examples
  : []
  ? id: 206
    description: You Found Me! (Debug Only)
  : []
  ? id: 311
    description: On
  : []
  ? id: 503
    description: Play A Second Video
  : []
  ? id: 401
    description: Next Scene
  : - !NewScene
      new_scene:
        id: 500
  ? id: 202
    description: Trigger Delayed Events
  : - !CueEvent
      event:
        delay:
          secs: 10
          nanos: 0
        event_id:
          id: 203
    - !CueEvent
      event:
        delay:
          secs: 11
          nanos: 0
        event_id:
          id: 204
    - !CueEvent
      event:
        delay:
          secs: 20
          nanos: 0
        event_id:
          id: 203
    - !CueEvent
      event:
        delay:
          secs: 30
          nanos: 0
        event_id:
          id: 203
    - !CueEvent
      event:
        delay:
          secs: 40
          nanos: 0
        event_id:
          id: 203
    - !CueEvent
      event:
        delay:
          secs: 50
          nanos: 0
        event_id:
          id: 203
  ? id: 510
    description: You Can Play Media As Well
  : null
  ? id: 314
    description: Turn Off
  : - !ModifyStatus
      status_id:
        id: 310
      new_state:
        id: 312
  ? id: 210
    description: That's an Event! Try Again ...
  : null
  ? id: 205
    description: This Event Does Nothing
  : []
  ? id: 201
    description: Next Scene
  : - !NewScene
      new_scene:
        id: 300
  ? id: 322
    description: Do Nothing
  : []
  ? id: 300
    description: Status Examples
  : []
  ? id: 323
    description: Activate
  : - !ModifyStatus
      status_id:
        id: 320
      new_state:
        id: 321
  ? id: 301
    description: Next Scene
  : - !NewScene
      new_scene:
        id: 400
  ? id: 500
    description: Media Examples
  : []
  ? id: 204
    description: Cancel Upcoming Events
  : - !CancelEvent
      event:
        id: 203
    - !CancelEvent
      event:
        id: 204
  ? id: 304
    description: Empty Event
  : []
  ? id: 110
    description: Click Below to Change Scenes
  : null
  ? id: 402
    description: Save 'Example String'
  : - !SaveData
      data: !StaticString
        string: Example String
  ? id: 200
    description: Event Examples
  : []
  ? id: 501
    description: Back To Introduction
  : - !NewScene
      new_scene:
        id: 100
user_styles:
  '#scene-100 #id-700 .groupArea': '{ width: 365px; height: 226px; }'
  '#scene-100 #id-1000': '{ left: 532px; top: 362px; }'
  '#scene-100 #id-700': '{ left: 379px; top: 96px; }'
  '#scene-200 #id-1000': '{ left: 591px; top: 365px; }'
  '#scene-100 #id-203': '{ left: 94px; top: 60px; }'
  '#scene-100 #id-101': '{ left: 58px; top: 51px; }'
